// Everything Android-framework-dependent lives here. This module could not be
// compile-verified while writing it: this sandbox's egress policy blocks dl.google.com
// entirely, which backs both the `google()` Gradle repository and every androidx.*/Play
// Services artifact, and there's no Android SDK installed either. First thing to do in
// Android Studio: let it sync, then fix whatever it flags — see NOTES.md at the repo root
// for the full rundown of what's verified vs. not.
import java.util.Properties
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    // AGP 9's built-in Kotlin support (see gradle.properties's android.builtInKotlin), not the
    // traditional org.jetbrains.kotlin.android plugin — nine failed attempts before this one,
    // each solving a real but wrong problem (full history in NOTES.md). Short version: a wrong
    // gradle.properties flag, a flag that didn't help, an AGP-8 retreat that hit a different
    // KGP-side check, then a built-in-Kotlin setup that kept crashing on BaseVariant regardless
    // of Kotlin version (2.2.10/2.3.20/2.4.10), module structure (multi- vs. single-module), or
    // root-level plugin co-declaration — all individually ruled out against a real Android
    // Studio sync, on a machine where a disposable Empty-Activity template generated by the same
    // Android Studio install syncs clean under the exact same AGP/Gradle/Kotlin versions.
    //
    // No explicit version here anymore (tenth attempt, see root build.gradle.kts): AGP is now
    // declared with `apply false` at the root instead, applied bare here — matching the standard
    // Android Studio template pattern exactly, rather than requesting an explicit version
    // directly in this subproject (a different plugin-resolution path, even though both resolve
    // the identical artifact coordinates).
    //
    // No org.jetbrains.kotlin.plugin.serialization either — the working template doesn't apply
    // it, and this module's only reason to (GithubReleaseDto, the update-checker DTO) moved to
    // :logic/api/GithubReleaseModels.kt instead, which already applies the serialization
    // compiler plugin for its own models and isn't an Android module, so it can never hit this
    // AGP/KGP conflict regardless of AGP's built-in Kotlin state. :app only needs the
    // kotlinx-serialization-json *runtime* dependency (still declared below) for Json{} and the
    // Retrofit converter factory, not the compiler plugin, since it has no @Serializable classes
    // of its own anymore.
    id("com.android.application")
    id("org.jetbrains.kotlin.plugin.compose")
}

// Release signing: keystore.properties (gitignored — see .gitignore) at the repo root, written
// by .github/workflows/release.yml from repo secrets right before assembleRelease runs. Never
// committed, and simply absent for any local/debug build, which is exactly why the signingConfig
// below is conditional rather than assumed to exist.
val keystorePropertiesFile = rootProject.file("keystore.properties")
val hasKeystoreProperties = keystorePropertiesFile.exists()
val keystoreProperties = Properties().apply {
    if (hasKeystoreProperties) load(keystorePropertiesFile.inputStream())
}

val sentryDsn = (project.findProperty("sentryDsn") as String?)?.trim().orEmpty()
val sentryEnabled = sentryDsn.isNotEmpty()

android {
    namespace = "com.routy.app"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.routy.app"
        minSdk = 26
        targetSdk = 36
        // Overridden by CI from the pushed release tag (-PappVersionName=0.13a -PappVersionCode=N)
        // — see .github/workflows/release.yml. Tags use the `a` suffix (e.g. v0.13a).
        versionCode = (project.findProperty("appVersionCode") as String?)?.toIntOrNull() ?: 19
        versionName = (project.findProperty("appVersionName") as String?) ?: "0.21a"
        buildConfigField("String", "SENTRY_DSN", "\"${sentryDsn.replace("\"", "\\\"")}\"")
    }

    signingConfigs {
        if (hasKeystoreProperties) {
            create("release") {
                storeFile = file(keystoreProperties.getProperty("storeFile"))
                storePassword = keystoreProperties.getProperty("storePassword")
                keyAlias = keystoreProperties.getProperty("keyAlias")
                keyPassword = keystoreProperties.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            if (hasKeystoreProperties) signingConfig = signingConfigs.getByName("release")
        }
        debug {
            applicationIdSuffix = ".debug"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
        // Off by default in AGP 8+ — turned on so the update checker (M6) can read
        // BuildConfig.VERSION_NAME to compare the running app against the latest GitHub release.
        buildConfig = true
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

// AGP's built-in Kotlin support (no org.jetbrains.kotlin.android applied — see the plugins
// block above) registers this top-level `kotlin` extension itself; compilerOptions here works
// the same as it would under the traditional plugin. Technically redundant — built-in Kotlin
// defaults jvmTarget to compileOptions.targetCompatibility (JVM_17, set below) on its own — but
// left explicit since that's what already matches this module's compileOptions.
kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

dependencies {
    implementation(project(":logic"))

    // --- Compose ---
    // 2026.06.01: current stable as of Aug 2026 (verified via WebSearch, since compose-bom is
    // Google-Maven-only and unreachable from this sandbox). Was pinned at 2024.12.01 originally
    // (unverifiable at the time — no compiler feedback loop existed) and turned out to be too
    // old to have Material3's standalone ExposedDropdownMenu composable, which RouteScreen.kt
    // uses — first real Android Studio build after the Gradle/AGP sync saga flagged it as
    // Unresolved reference.
    val composeBom = platform("androidx.compose:compose-bom:2026.06.01")
    implementation(composeBom)
    androidTestImplementation(composeBom)
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    debugImplementation("androidx.compose.ui:ui-tooling")

    implementation("androidx.core:core-ktx:1.15.0")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.7")
    implementation("androidx.activity:activity-compose:1.9.3")
    implementation("androidx.navigation:navigation-compose:2.8.5")

    // --- Networking ---
    implementation("com.squareup.retrofit2:retrofit:2.11.0")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")
    // com.squareup.retrofit2:converter-kotlinx-serialization, not the old third-party
    // com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter (which this used
    // originally) — that project was folded into Retrofit itself as of 2.10.0, and while the
    // old artifact still resolves fine as a dependency (verified: it's real, downloadable, and
    // this project's :app builds packaged its .jar), its classes never actually became visible
    // to compileDebugKotlin — first real Android Studio build after the Gradle/AGP sync saga
    // flagged every retrofit2.converter.kotlinx.serialization.* import as Unresolved reference.
    // Pinned to the exact same version as the main retrofit artifact above, matching Square's
    // own versioning convention for all retrofit-converters — same package name
    // (retrofit2.converter.kotlinx.serialization), verified directly against the published jar,
    // so no import changes needed in ApiClientProvider.kt/GithubReleaseClient.kt.
    implementation("com.squareup.retrofit2:converter-kotlinx-serialization:2.11.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")

    // --- Secure token/server-URL storage ---
    implementation("androidx.security:security-crypto:1.1.0-alpha06")

    // --- Background upload retry (E3) ---
    implementation("androidx.work:work-runtime-ktx:2.10.0")

    // --- Location (foreground recording, M4) ---
    implementation("com.google.android.gms:play-services-location:21.3.0")

    // --- Map (M3) ---
    // 12.3.1, not 10.2.0: MapLibre renamed com.mapbox.mapboxsdk.* to org.maplibre.android.* at v11.0.0 —
    // 10.2.0 predates that rename
    // and still ships the old namespace, which is why every org.maplibre.android.*/
    // org.maplibre.geojson.* import this codebase uses (written assuming the *new* namespace)
    // came back Unresolved reference on the first real compile. 12.3.1 is the latest stable
    // release before v13.0.0's architecture change (Vulkan becomes the default rendering
    // backend, OpenGL ES moves to a separate android-sdk-opengl artifact, GeoJsonSource's sync
    // update API changes) — picked deliberately to land on the *last* version where this
    // module's existing MapView/Style/Layer/GeoJsonSource usage needs no further code changes
    // beyond the version bump itself, verified directly: downloaded the AAR and confirmed every
    // class this module imports (MapView, MapLibreMap, Style, CircleLayer, LineLayer,
    // PropertyFactory, GeoJsonSource, CameraUpdateFactory, LatLng, LatLngBounds, Expression,
    // Property, MapLibre) is present, with org.maplibre.geojson.* (Feature, FeatureCollection,
    // LineString, Point) pulled in transitively via this artifact's own dependency on
    // org.maplibre.gl:android-sdk-geojson.
    implementation("org.maplibre.gl:android-sdk:12.3.1")

    // --- Crash reporting (optional — only packaged when -PsentryDsn is set at build time) ---
    if (sentryEnabled) {
        implementation("io.sentry:sentry-android:8.12.0")
    } else {
        compileOnly("io.sentry:sentry-android:8.12.0")
    }

    // --- Tests ---
    testImplementation(kotlin("test-junit5"))
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.11.3")
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.6.1")
}
